"""
C generator - Stars
"""

from typing import Optional


def generate_star_c(
    star_id: str,
    name: Optional[str] = None,
    spectral_class: str = "G",
    mass_solar: float = 1.0,
    age_billion_years: float = 0,
    life_stage: str = "main_sequence",
    planet_count: int = 0,
    habitable_zone_inner_au: float = 0.9,
    habitable_zone_outer_au: float = 1.4,
    formed_at_commit: int = 0,
    luminosity_solar: float = 1.0,
    temperature_kelvin: int = 5778
) -> str:
    """Generate a star.c file"""
    
    name_str = name if name else ""
    life_stage_enum = f"STAGE_{life_stage.upper()}"
    spectral_enum = f"SPECTRAL_{spectral_class.upper()}"
    
    return f'''/**
 * Star System Definition
 * Generated by Commit Universe Engine
 * 
 * {star_id}
 */

#ifndef STAR_{star_id.upper().replace("-", "_")}_H
#define STAR_{star_id.upper().replace("-", "_")}_H

/* Spectral Classifications */
typedef enum {{
    SPECTRAL_O,  /* Blue giants, >30,000K */
    SPECTRAL_B,  /* Blue-white, 10,000-30,000K */
    SPECTRAL_A,  /* White, 7,500-10,000K */
    SPECTRAL_F,  /* Yellow-white, 6,000-7,500K */
    SPECTRAL_G,  /* Yellow (Sun-like), 5,200-6,000K */
    SPECTRAL_K,  /* Orange, 3,700-5,200K */
    SPECTRAL_M   /* Red dwarfs, 2,400-3,700K */
}} SpectralClass;

/* Stellar Evolution Stages */
typedef enum {{
    STAGE_PROTOSTAR,
    STAGE_MAIN_SEQUENCE,
    STAGE_SUBGIANT,
    STAGE_RED_GIANT,
    STAGE_HORIZONTAL_BRANCH,
    STAGE_ASYMPTOTIC_GIANT,
    STAGE_PLANETARY_NEBULA,
    STAGE_WHITE_DWARF,
    STAGE_NEUTRON_STAR,
    STAGE_BLACK_HOLE
}} LifeStage;

/* Star Data Structure */
struct Star {{
    char            id[32];
    char            name[64];
    SpectralClass   spectral_class;
    double          mass_solar;
    double          age_billion_years;
    LifeStage       life_stage;
    int             planet_count;
    double          habitable_zone_inner_au;
    double          habitable_zone_outer_au;
    double          luminosity_solar;
    int             temperature_kelvin;
    unsigned long   formed_at_commit;
}};

/* Star Instance */
static const struct Star STAR_DATA = {{
    .id                     = "{star_id}",
    .name                   = "{name_str}",
    .spectral_class         = {spectral_enum},
    .mass_solar             = {mass_solar:.4f},
    .age_billion_years      = {age_billion_years:.2f},
    .life_stage             = {life_stage_enum},
    .planet_count           = {planet_count},
    .habitable_zone_inner_au = {habitable_zone_inner_au:.2f},
    .habitable_zone_outer_au = {habitable_zone_outer_au:.2f},
    .luminosity_solar       = {luminosity_solar:.4f},
    .temperature_kelvin     = {temperature_kelvin},
    .formed_at_commit       = {formed_at_commit}
}};

/* Helper Functions */
static inline int star_has_name(const struct Star* s) {{
    return s->name[0] != '\\0';
}}

static inline int star_is_habitable(const struct Star* s) {{
    return s->life_stage == STAGE_MAIN_SEQUENCE && 
           s->spectral_class >= SPECTRAL_F && 
           s->spectral_class <= SPECTRAL_K;
}}

#endif /* STAR_{star_id.upper().replace("-", "_")}_H */
'''
