"""
Esoteric language generators - Anomalies (Brainfuck) and Ancient Ruins (COBOL)

These languages are used for weird cosmic phenomena and ancient artifacts
to give them an appropriately strange or archaic feel.
"""

from typing import Optional, List
import random


def generate_anomaly_bf(
    anomaly_id: str,
    anomaly_type: str = "unknown",
    location: str = "unknown",
    danger_level: int = 5,
    discovered_at_commit: int = 0,
    properties: Optional[List[str]] = None,
    notes: Optional[str] = None
) -> str:
    """
    Generate a Brainfuck file for cosmic anomalies.
    
    The Brainfuck code is decorative but actually encodes the anomaly ID
    when run (theoretically). The real data is in the comments.
    """
    
    if properties is None:
        properties = ["UNKNOWN PROPERTIES"]
    
    # Generate some mystical-looking Brainfuck based on the anomaly
    bf_code = _generate_mystical_brainfuck(anomaly_id, danger_level)
    
    danger_warnings = {
        1: "SAFE - Minimal risk",
        2: "CAUTION - Minor spatial distortions",
        3: "WARNING - Significant anomalous activity",
        4: "DANGER - Reality destabilization possible",
        5: "SEVERE - Do not approach without authorization",
        6: "EXTREME - Quarantine zone established",
        7: "CRITICAL - Reality anchor required",
        8: "CATASTROPHIC - Existential threat level",
        9: "OMEGA - Universe-scale implications",
        10: "UNDEFINED - Beyond classification"
    }
    
    warning = danger_warnings.get(danger_level, "UNKNOWN THREAT LEVEL")
    properties_list = "\n".join([f"    - {p}" for p in properties])
    notes_section = f"\nNOTES: {notes}" if notes else ""
    
    return f'''ANOMALY RECORD: {anomaly_id}
=====================================
Classification: {anomaly_type.upper()}
Location: {location}
Danger Level: {danger_level}/10 - {warning}

First Detected: Commit #{discovered_at_commit}
Status: ACTIVE

Properties:
{properties_list}
{notes_section}

--- ENCODED SIGNATURE BEGIN ---
The following encodes the anomaly's quantum signature.
Do not attempt to execute on standard hardware.

{bf_code}

--- ENCODED SIGNATURE END ---

WARNING: This anomaly defies conventional physics.
Standard causality may not apply in proximity.
Report all observations to the Universal Archives.

=====================================
File format: Brainfuck (decorative encoding)
Generated by Commit Universe Engine
'''


def _generate_mystical_brainfuck(anomaly_id: str, intensity: int) -> str:
    """Generate mystical-looking Brainfuck code"""
    
    # Basic patterns that look appropriately arcane
    patterns = [
        "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]",
        ">>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.",
        "[->+>+<<]>>[-<<+>>]<<<[->>>+<<<]>>>[-<<<+>>>]",
        ">>++++[<++++[<++++>-]>-]<<.[-]",
        "+[-->-[>>+>-----<<]<--<---]>-.>>>+.>>..+++[.>]<<<<.+++.------.<<-.>>>>+.",
    ]
    
    # Build up code based on intensity
    lines = []
    num_lines = 3 + intensity // 2
    
    for i in range(num_lines):
        # Mix patterns with some randomization based on anomaly_id
        seed = hash(f"{anomaly_id}_{i}") % len(patterns)
        pattern = patterns[seed]
        
        # Add some variations
        if i % 2 == 0:
            pattern = pattern.replace("+", "+" * (1 + intensity // 3))
        if i % 3 == 0:
            pattern = ">" * (intensity // 2) + pattern + "<" * (intensity // 2)
            
        lines.append(pattern)
    
    return "\n".join(lines)


def generate_ruins_cob(
    ruins_id: str,
    location: str,
    builder_civilization: str = "UNKNOWN",
    age_commits: int = 0,
    discovered_at_commit: int = 0,
    translation_status: str = "NONE",
    danger_level: int = 1,
    artifacts_found: int = 0,
    inscriptions: Optional[List[str]] = None,
    purpose: str = "UNKNOWN"
) -> str:
    """
    Generate a COBOL file for ancient ruins.
    
    COBOL's verbose, archaic style perfectly captures the feel of
    ancient alien artifacts and archaeological records.
    """
    
    if inscriptions is None:
        inscriptions = ["[UNTRANSLATED]"]
    
    # Format inscriptions for COBOL
    inscriptions_section = _format_cobol_inscriptions(inscriptions)
    
    # Danger assessment
    danger_assessment = _get_danger_assessment(danger_level)
    
    return f'''       IDENTIFICATION DIVISION.
       PROGRAM-ID. RUINS-{ruins_id.upper().replace("-", "")}.
       AUTHOR. UNIVERSAL-ARCHIVES.
       DATE-WRITTEN. COMMIT-{discovered_at_commit}.
      *
      * ============================================
      * ANCIENT RUINS ARCHAEOLOGICAL RECORD
      * ============================================
      * 
      * SITE: {ruins_id}
      * STATUS: UNDER INVESTIGATION
      *
       
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. UNIVERSAL-ARCHIVES-MAINFRAME.
       OBJECT-COMPUTER. ARCHAEOLOGICAL-SURVEY-UNIT.
       
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       
      * --- SITE IDENTIFICATION ---
       01 RUINS-RECORD.
          05 RUINS-ID            PIC X(32)  VALUE "{ruins_id}".
          05 SITE-LOCATION       PIC X(256) VALUE
             "{location}".
          05 FILLER              PIC X(8)   VALUE SPACES.
             
      * --- BUILDER INFORMATION ---
       01 BUILDER-DATA.
          05 BUILDER-CIV         PIC X(64)  VALUE "{builder_civilization}".
          05 BUILDER-STATUS      PIC X(16)  VALUE "EXTINCT".
          05 BUILDER-TECH-LEVEL  PIC 9(2)   VALUE 00.
          
      * --- TEMPORAL DATA ---
       01 TEMPORAL-RECORD.
          05 AGE-IN-COMMITS      PIC 9(12)  VALUE {age_commits:012d}.
          05 DISCOVERED-COMMIT   PIC 9(12)  VALUE {discovered_at_commit:012d}.
          05 ESTIMATED-AGE-MYR   PIC 9(8)   VALUE 00000000.
          
      * --- SURVEY STATUS ---
       01 SURVEY-DATA.
          05 TRANSLATION-STATUS  PIC X(16)  VALUE "{translation_status}".
          05 DANGER-LEVEL        PIC 9(2)   VALUE {danger_level:02d}.
          05 DANGER-ASSESSMENT   PIC X(32)  VALUE "{danger_assessment}".
          05 ARTIFACTS-FOUND     PIC 9(8)   VALUE {artifacts_found:08d}.
          05 SURVEY-COMPLETE-PCT PIC 9(3)   VALUE 000.
          
      * --- STRUCTURE DATA ---
       01 STRUCTURE-ANALYSIS.
          05 PRIMARY-PURPOSE     PIC X(32)  VALUE "{purpose}".
          05 STRUCTURAL-INTACT   PIC 9(3)   VALUE 000.
          05 POWER-SOURCE-ACTIVE PIC X(3)   VALUE "NO ".
          05 DEFENSIVE-SYSTEMS   PIC X(3)   VALUE "UNK".
          
      * --- INSCRIPTIONS ---
{inscriptions_section}
       
       PROCEDURE DIVISION.
       
       MAIN-PROCEDURE.
           DISPLAY "========================================".
           DISPLAY "ANCIENT RUINS SURVEY RECORD".
           DISPLAY "========================================".
           DISPLAY " ".
           DISPLAY "SITE ID: " RUINS-ID.
           DISPLAY "LOCATION: " SITE-LOCATION.
           DISPLAY "BUILDERS: " BUILDER-CIV.
           DISPLAY " ".
           DISPLAY "AGE: " AGE-IN-COMMITS " COMMITS".
           DISPLAY "ARTIFACTS: " ARTIFACTS-FOUND.
           DISPLAY "DANGER LEVEL: " DANGER-LEVEL " - " 
                   DANGER-ASSESSMENT.
           DISPLAY " ".
           DISPLAY "PRIMARY PURPOSE: " PRIMARY-PURPOSE.
           DISPLAY "TRANSLATION: " TRANSLATION-STATUS.
           DISPLAY " ".
           PERFORM DISPLAY-INSCRIPTIONS.
           DISPLAY " ".
           DISPLAY "========================================".
           DISPLAY "END OF RECORD".
           DISPLAY "========================================".
           STOP RUN.
           
       DISPLAY-INSCRIPTIONS.
           DISPLAY "--- RECOVERED INSCRIPTIONS ---".
           DISPLAY INSCRIPTION-LINE-01.
           DISPLAY INSCRIPTION-LINE-02.
           DISPLAY INSCRIPTION-LINE-03.
           DISPLAY "--- END INSCRIPTIONS ---".
           
      * ============================================
      * THE BUILDERS ARE GONE
      * BUT THEIR WORKS REMAIN
      * WHAT WERE THEY TRYING TO TELL US?
      * ============================================
'''


def _format_cobol_inscriptions(inscriptions: List[str]) -> str:
    """Format inscriptions as COBOL data items"""
    lines = ["       01 INSCRIPTION-DATA."]
    
    for i, inscription in enumerate(inscriptions[:5], 1):  # Max 5 inscriptions
        # Truncate and pad to 64 chars
        text = inscription[:64].ljust(64)
        lines.append(f'          05 INSCRIPTION-LINE-{i:02d} PIC X(64) VALUE')
        lines.append(f'             "{text}".')
    
    # Pad remaining slots
    for i in range(len(inscriptions) + 1, 6):
        lines.append(f'          05 INSCRIPTION-LINE-{i:02d} PIC X(64) VALUE SPACES.')
    
    return "\n".join(lines)


def _get_danger_assessment(level: int) -> str:
    """Get danger assessment text for ruins"""
    assessments = {
        1: "SAFE-INERT",
        2: "LOW-CAUTION ADVISED",
        3: "MODERATE-TEAM REQUIRED",
        4: "ELEVATED-ARMED ESCORT",
        5: "HIGH-SPECIALIST ONLY",
        6: "SEVERE-QUARANTINE",
        7: "CRITICAL-REMOTE ONLY",
        8: "EXTREME-NO ENTRY",
        9: "MAXIMUM-ORBITAL WATCH",
        10: "FORBIDDEN-SEALED"
    }
    return assessments.get(level, "UNKNOWN")


# Additional mysterious artifact generator
def generate_artifact_record(
    artifact_id: str,
    found_at: str,
    artifact_type: str = "UNKNOWN",
    properties: Optional[List[str]] = None
) -> str:
    """Generate a short artifact record in a pseudo-ancient format"""
    
    if properties is None:
        properties = ["ANOMALOUS"]
    
    props = " | ".join(properties)
    
    return f'''
+------------------------------------------+
| ARTIFACT: {artifact_id:<30} |
+------------------------------------------+
| TYPE: {artifact_type:<34} |
| ORIGIN: {found_at:<32} |
| PROPERTIES: {props:<28} |
| STATUS: CONTAINED                        |
+------------------------------------------+
| HANDLE WITH EXTREME CAUTION              |
+------------------------------------------+
'''
