"""
JavaScript generator - Life
"""

from typing import List, Optional, Dict


def generate_life_js(
    planet_id: str,
    emerged_at_commit: int = 0,
    origin: str = "abiogenesis",
    stage: str = "single_cell",
    domains: int = 1,
    species_count: int = 1,
    milestones: Optional[List[Dict]] = None,
    dominant_form: Optional[Dict] = None,
    extinction_events: int = 0,
    biodiversity_index: float = 0.1
) -> str:
    """Generate a life.js file"""
    
    if milestones is None:
        milestones = [
            {"commit": emerged_at_commit, "event": "first self-replicating molecules"}
        ]
    
    if dominant_form is None:
        dominant_form = {
            "type": "microbial",
            "locomotion": "none",
            "respiration": "chemosynthesis",
            "avg_lifespan_years": 0.001
        }
    
    milestones_js = ",\n        ".join([
        f'{{ commit: {m["commit"]}, event: "{m["event"]}" }}'
        for m in milestones
    ])
    
    return f'''/**
 * Life on {planet_id}
 * Generated by Commit Universe Engine
 * 
 * Status: {stage.replace("_", " ").title()}
 */

const life = {{
    // Location
    planet_id: "{planet_id}",
    
    // Origins
    emerged_at_commit: {emerged_at_commit},
    origin: "{origin}",  // abiogenesis, panspermia, seeded, engineered
    
    // Current evolutionary state
    stage: "{stage}",
    /*
     * Stages:
     * - prebiotic: Complex chemistry, not yet life
     * - single_cell: Prokaryotic life
     * - complex_single_cell: Eukaryotic life
     * - multicellular: Simple multicellular organisms
     * - complex_multicellular: Diverse complex life
     * - intelligent: Tool-using species present
     * - civilized: Organized societies
     * - spacefaring: Space-capable civilization
     * - transcendent: Post-biological
     * - extinct: All life ended
     */
    
    // Biodiversity
    domains: {domains},
    species_count: {species_count:_},
    biodiversity_index: {biodiversity_index:.2f},  // 0-1 scale
    
    // Evolutionary history
    milestones: [
        {milestones_js}
    ],
    
    // Dominant life form
    dominant_form: {{
        type: "{dominant_form['type']}",
        locomotion: "{dominant_form['locomotion']}",
        respiration: "{dominant_form['respiration']}",
        avg_lifespan_years: {dominant_form['avg_lifespan_years']}
    }},
    
    // Catastrophes survived
    extinction_events: {extinction_events},
    
    // Methods
    isIntelligent() {{
        return ["intelligent", "civilized", "spacefaring", "transcendent"].includes(this.stage);
    }},
    
    isExtinct() {{
        return this.stage === "extinct";
    }},
    
    getAge(currentCommit) {{
        return currentCommit - this.emerged_at_commit;
    }},
    
    getSummary() {{
        const status = this.isExtinct() ? "EXTINCT" : this.stage.toUpperCase();
        return `Life on ${{this.planet_id}}: ${{status}}, ${{this.species_count.toLocaleString()}} species`;
    }}
}};

// For Node.js environments
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = life;
}}

// For browser environments
if (typeof window !== 'undefined') {{
    window.lifeData = life;
}}
'''
