"""
JavaScript generator - Life and Ecosystems

Generates ecosystem.js files that track:
- Overall ecosystem status
- Fauna evolution stage
- Flora evolution stage
- Biome distribution
- Notable species
- Mass extinction history
"""

from typing import List, Optional, Dict, Any
from dataclasses import asdict

from .creature_gen import Creature, Flora, BiologyType


def generate_ecosystem_js(
    planet_id: str,
    emerged_at_commit: int = 0,
    origin: str = "abiogenesis",
    biology_type: str = "carbon",
    fauna_stage: str = "single_cell",
    flora_stage: str = "microbial_mats",
    fauna_diversity: int = 1,
    flora_diversity: int = 1,
    biomes: Optional[List[str]] = None,
    apex_predators: Optional[List[Dict]] = None,
    notable_species: Optional[List[Dict]] = None,
    notable_flora: Optional[List[Dict]] = None,
    mass_extinctions: Optional[List[Dict]] = None,
    milestones: Optional[List[Dict]] = None,
    biodiversity_index: float = 0.1,
    ecosystem_status: str = "developing",
) -> str:
    """Generate a comprehensive ecosystem.js file"""

    if biomes is None:
        biomes = ["ocean_shallow"]

    if apex_predators is None:
        apex_predators = []

    if notable_species is None:
        notable_species = []

    if notable_flora is None:
        notable_flora = []

    if mass_extinctions is None:
        mass_extinctions = []

    if milestones is None:
        milestones = [
            {"commit": emerged_at_commit, "event": "first self-replicating molecules"}
        ]

    # Format arrays for JS
    biomes_js = ", ".join([f'"{b}"' for b in biomes])

    milestones_js = ",\n        ".join([
        f'{{ commit: {m["commit"]}, event: "{m["event"]}" }}'
        for m in milestones
    ])

    extinctions_js = ",\n        ".join([
        f'''{{
            commit: {e.get("commit", 0)},
            name: "{e.get("name", "Unknown Event")}",
            cause: "{e.get("cause", "unknown")}",
            severity: {e.get("severity", 0.5)},
            species_lost_percent: {e.get("species_lost_percent", 50)}
        }}'''
        for e in mass_extinctions
    ]) if mass_extinctions else ""

    apex_js = ",\n        ".join([
        f'''{{
            id: "{a.get("id", "")}",
            name: "{a.get("name", "Unknown")}",
            category: "{a.get("category", "terrestrial")}",
            size: "{a.get("size", "large")}",
            status: "{a.get("status", "common")}"
        }}'''
        for a in apex_predators
    ]) if apex_predators else ""

    species_js = ",\n        ".join([
        f'''{{
            id: "{s.get("id", "")}",
            name: "{s.get("name", "Unknown")}",
            category: "{s.get("category", "terrestrial")}",
            role: "{s.get("role", "herbivore")}",
            intelligence: "{s.get("intelligence", "primitive")}"
        }}'''
        for s in notable_species
    ]) if notable_species else ""

    flora_js = ",\n        ".join([
        f'''{{
            id: "{f.get("id", "")}",
            name: "{f.get("name", "Unknown")}",
            type: "{f.get("type", "plant")}",
            coverage: "{f.get("coverage", "common")}"
        }}'''
        for f in notable_flora
    ]) if notable_flora else ""

    return f'''/**
 * Ecosystem of {planet_id}
 * Generated by Commit Universe Engine
 *
 * Biology: {biology_type.replace("_", " ").title()}
 * Status: {ecosystem_status.title()}
 */

const ecosystem = {{
    // === IDENTIFICATION ===
    planet_id: "{planet_id}",
    emerged_at_commit: {emerged_at_commit},
    origin: "{origin}",  // abiogenesis, panspermia, seeded, engineered

    // === BIOLOGY TYPE ===
    biology_type: "{biology_type}",
    /*
     * Types: carbon, silicon, ammonia, methane, sulfur, crystalline, energy, machine
     */

    // === ECOSYSTEM STATUS ===
    status: "{ecosystem_status}",  // barren, prebiotic, developing, thriving, declining, dying, dead
    biodiversity_index: {biodiversity_index:.3f},  // 0-1 scale

    // === FAUNA (ANIMAL LIFE) ===
    fauna: {{
        stage: "{fauna_stage}",
        /*
         * Stages:
         * barren -> prebiotic -> primordial_soup -> single_cell ->
         * multicellular_simple -> aquatic_primitive -> aquatic_complex ->
         * amphibian -> reptilian -> megafauna -> mammalian ->
         * primate -> intelligent -> civilized
         */
        diversity: {fauna_diversity:_},  // Estimated species count

        apex_predators: [
            {apex_js}
        ],

        notable_species: [
            {species_js}
        ]
    }},

    // === FLORA (PLANT LIFE) ===
    flora: {{
        stage: "{flora_stage}",
        /*
         * Stages:
         * none -> microbial_mats -> algae -> moss_lichen ->
         * ferns -> forests -> flowering -> mega_flora
         */
        diversity: {flora_diversity:_},  // Estimated species count

        notable_flora: [
            {flora_js}
        ]
    }},

    // === BIOMES ===
    biomes: [{biomes_js}],
    /*
     * Types: ocean_deep, ocean_shallow, coastal, wetland, tropical_forest,
     * temperate_forest, boreal_forest, grassland, savanna, desert_hot,
     * desert_cold, tundra, mountain, volcanic, ice_sheet, underground
     */

    // === EVOLUTIONARY HISTORY ===
    milestones: [
        {milestones_js}
    ],

    // === MASS EXTINCTIONS ===
    mass_extinctions: [
        {extinctions_js}
    ],
    extinction_count: {len(mass_extinctions)},

    // === METHODS ===
    hasLife() {{
        return !["barren", "prebiotic", "dead"].includes(this.status);
    }},

    hasComplexLife() {{
        const complexStages = ["aquatic_complex", "amphibian", "reptilian",
                              "megafauna", "mammalian", "primate", "intelligent", "civilized"];
        return complexStages.includes(this.fauna.stage);
    }},

    hasIntelligentLife() {{
        return ["intelligent", "civilized"].includes(this.fauna.stage);
    }},

    isExtinct() {{
        return this.status === "dead";
    }},

    getAge(currentCommit) {{
        return currentCommit - this.emerged_at_commit;
    }},

    getSummary() {{
        if (!this.hasLife()) return `${{this.planet_id}}: No life`;
        const status = this.isExtinct() ? "EXTINCT" : this.fauna.stage.toUpperCase();
        return `${{this.planet_id}}: ${{status}}, ${{this.fauna.diversity.toLocaleString()}} fauna, ${{this.flora.diversity.toLocaleString()}} flora`;
    }},

    getThreatLevel() {{
        // Calculate extinction risk based on various factors
        let threat = 0;
        if (this.biodiversity_index < 0.3) threat += 0.3;
        if (this.extinction_count > 3) threat += 0.2;
        if (this.status === "declining") threat += 0.3;
        if (this.status === "dying") threat += 0.5;
        return Math.min(threat, 1.0);
    }}
}};

// For Node.js environments
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = ecosystem;
}}

// For browser environments
if (typeof window !== 'undefined') {{
    window.ecosystemData = ecosystem;
}}
'''


def generate_life_js(
    planet_id: str,
    emerged_at_commit: int = 0,
    origin: str = "abiogenesis",
    stage: str = "single_cell",
    domains: int = 1,
    species_count: int = 1,
    milestones: Optional[List[Dict]] = None,
    dominant_form: Optional[Dict] = None,
    extinction_events: int = 0,
    biodiversity_index: float = 0.1
) -> str:
    """Generate a legacy life.js file (for backward compatibility)"""

    if milestones is None:
        milestones = [
            {"commit": emerged_at_commit, "event": "first self-replicating molecules"}
        ]

    if dominant_form is None:
        dominant_form = {
            "type": "microbial",
            "locomotion": "none",
            "respiration": "chemosynthesis",
            "avg_lifespan_years": 0.001
        }

    milestones_js = ",\n        ".join([
        f'{{ commit: {m["commit"]}, event: "{m["event"]}" }}'
        for m in milestones
    ])

    return f'''/**
 * Life on {planet_id}
 * Generated by Commit Universe Engine
 *
 * Status: {stage.replace("_", " ").title()}
 */

const life = {{
    // Location
    planet_id: "{planet_id}",

    // Origins
    emerged_at_commit: {emerged_at_commit},
    origin: "{origin}",  // abiogenesis, panspermia, seeded, engineered

    // Current evolutionary state
    stage: "{stage}",
    /*
     * Stages:
     * - prebiotic: Complex chemistry, not yet life
     * - single_cell: Prokaryotic life
     * - complex_single_cell: Eukaryotic life
     * - multicellular: Simple multicellular organisms
     * - complex_multicellular: Diverse complex life
     * - intelligent: Tool-using species present
     * - civilized: Organized societies
     * - spacefaring: Space-capable civilization
     * - transcendent: Post-biological
     * - extinct: All life ended
     */

    // Biodiversity
    domains: {domains},
    species_count: {species_count:_},
    biodiversity_index: {biodiversity_index:.2f},  // 0-1 scale

    // Evolutionary history
    milestones: [
        {milestones_js}
    ],

    // Dominant life form
    dominant_form: {{
        type: "{dominant_form['type']}",
        locomotion: "{dominant_form['locomotion']}",
        respiration: "{dominant_form['respiration']}",
        avg_lifespan_years: {dominant_form['avg_lifespan_years']}
    }},

    // Catastrophes survived
    extinction_events: {extinction_events},

    // Methods
    isIntelligent() {{
        return ["intelligent", "civilized", "spacefaring", "transcendent"].includes(this.stage);
    }},

    isExtinct() {{
        return this.stage === "extinct";
    }},

    getAge(currentCommit) {{
        return currentCommit - this.emerged_at_commit;
    }},

    getSummary() {{
        const status = this.isExtinct() ? "EXTINCT" : this.stage.toUpperCase();
        return `Life on ${{this.planet_id}}: ${{status}}, ${{this.species_count.toLocaleString()}} species`;
    }}
}};

// For Node.js environments
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = life;
}}

// For browser environments
if (typeof window !== 'undefined') {{
    window.lifeData = life;
}}
'''


def generate_creature_json(creature: Creature) -> str:
    """Generate a JSON file for a notable creature"""
    return f'''{{
    "id": "{creature.id}",
    "common_name": "{creature.common_name}",
    "scientific_name": "{creature.scientific_name}",

    "classification": {{
        "category": "{creature.category.value}",
        "role": "{creature.role.value}",
        "size_class": "{creature.size_class.value}",
        "intelligence": "{creature.intelligence.value}"
    }},

    "physical": {{
        "body_plan": "{creature.body_plan}",
        "locomotion": "{creature.locomotion}",
        "limb_count": {creature.limb_count},
        "has_tail": {str(creature.has_tail).lower()},
        "has_wings": {str(creature.has_wings).lower()},
        "coloration": {creature.coloration}
    }},

    "adaptations": {{
        "sensory": {creature.sensory_adaptations},
        "defensive": {creature.defensive_adaptations},
        "offensive": {creature.offensive_adaptations},
        "special": {creature.special_traits}
    }},

    "biology": {{
        "type": "{creature.biology_type.value}",
        "respiration": "{creature.respiration}",
        "diet": "{creature.diet}",
        "lifespan_years": {creature.lifespan_years:.1f},
        "reproduction": "{creature.reproduction}"
    }},

    "ecology": {{
        "habitat": "{creature.habitat}",
        "population_status": "{creature.population_status}"
    }},

    "discovered_at_commit": {creature.discovered_at_commit},
    "description": "{creature.description.replace('"', '\\"')}"
}}'''


def generate_flora_json(flora: Flora) -> str:
    """Generate a JSON file for notable flora"""
    return f'''{{
    "id": "{flora.id}",
    "common_name": "{flora.common_name}",
    "scientific_name": "{flora.scientific_name}",

    "physical": {{
        "growth_form": "{flora.growth_form}",
        "height_meters": {flora.height_meters:.1f},
        "coloration": {flora.coloration}
    }},

    "biology": {{
        "type": "{flora.biology_type.value}",
        "photosynthesis_type": "{flora.photosynthesis_type}",
        "reproduction": "{flora.reproduction}",
        "lifespan_years": {flora.lifespan_years:.1f}
    }},

    "ecology": {{
        "habitat": "{flora.habitat}",
        "coverage": "{flora.coverage}"
    }},

    "special_traits": {flora.special_traits},
    "discovered_at_commit": {flora.discovered_at_commit},
    "description": "{flora.description.replace('"', '\\"')}"
}}'''
