"""
JSON generator - Atmospheres
"""

import json
from typing import Dict, List, Optional


def generate_atmosphere_json(
    planet_id: str,
    pressure_atm: float = 1.0,
    composition: Optional[Dict[str, float]] = None,
    layers: Optional[List[Dict]] = None,
    average_temp_kelvin: int = 288,
    greenhouse_effect: bool = False,
    ozone_layer: bool = False,
    formed_at_commit: int = 0,
    breathable: bool = False,
    weather_active: bool = False
) -> str:
    """Generate an atmosphere.json file"""
    
    if composition is None:
        composition = {
            "nitrogen": 0.78,
            "oxygen": 0.21,
            "argon": 0.01
        }
    
    if layers is None:
        layers = [
            {"name": "troposphere", "height_km": 12, "temp_gradient": -6.5},
            {"name": "stratosphere", "height_km": 50, "temp_gradient": 1.0},
            {"name": "mesosphere", "height_km": 85, "temp_gradient": -2.5},
            {"name": "thermosphere", "height_km": 600, "temp_gradient": 2.0}
        ]
    
    data = {
        "_comment": f"Atmosphere data for {planet_id} - Generated by Commit Universe Engine",
        "planet_id": planet_id,
        "pressure_atm": pressure_atm,
        "composition": composition,
        "composition_notes": _generate_composition_notes(composition),
        "layers": layers,
        "properties": {
            "average_temp_kelvin": average_temp_kelvin,
            "average_temp_celsius": average_temp_kelvin - 273,
            "greenhouse_effect": greenhouse_effect,
            "ozone_layer": ozone_layer,
            "breathable": breathable,
            "weather_active": weather_active,
            "wind_speed_avg_kmh": 15 if weather_active else 0
        },
        "formed_at_commit": formed_at_commit,
        "last_updated_commit": formed_at_commit,
        "notable_events": []
    }
    
    return json.dumps(data, indent=2)


def _generate_composition_notes(composition: Dict[str, float]) -> str:
    """Generate human-readable notes about atmosphere composition"""
    notes = []
    
    if composition.get("oxygen", 0) > 0.15:
        notes.append("Oxygen-rich, potentially breathable")
    if composition.get("carbon_dioxide", 0) > 0.5:
        notes.append("Strong greenhouse atmosphere")
    if composition.get("methane", 0) > 0.01:
        notes.append("Methane detected, possible biological source")
    if composition.get("hydrogen", 0) > 0.5:
        notes.append("Hydrogen-dominated, gas giant type")
    if composition.get("sulfur_dioxide", 0) > 0.001:
        notes.append("Volcanic activity indicated")
    
    return "; ".join(notes) if notes else "Standard atmosphere"


def update_atmosphere_json(existing: str, changes: Dict) -> str:
    """Update an existing atmosphere.json with new data"""
    data = json.loads(existing)
    
    for key, value in changes.items():
        if key in data:
            if isinstance(data[key], dict) and isinstance(value, dict):
                data[key].update(value)
            else:
                data[key] = value
    
    return json.dumps(data, indent=2)
