"""
Lua generator - Moons
"""

from typing import Optional


def generate_moon_lua(
    moon_id: str,
    name: Optional[str] = None,
    parent_planet: str = "unknown",
    mass_luna: float = 1.0,
    radius_km: float = 1737,
    orbital_period_days: float = 27.3,
    tidally_locked: bool = True,
    composition: str = "silicate",
    crater_count: int = 0,
    formed_at_commit: int = 0,
    formed_by: str = "accretion"
) -> str:
    """Generate a moon.lua file"""
    
    name_value = f'"{name}"' if name else "nil"
    tidally_str = "true" if tidally_locked else "false"
    
    return f'''--[[
    Moon Definition
    Generated by Commit Universe Engine
    
    {moon_id}
--]]

local Moon = {{
    -- Identity
    id = "{moon_id}",
    name = {name_value},
    parent_planet = "{parent_planet}",
    
    -- Physical properties
    mass_luna = {mass_luna:.6f},        -- relative to Earth's Moon
    radius_km = {radius_km:.1f},
    density_g_cm3 = 3.34,
    
    -- Orbital properties
    orbital_period_days = {orbital_period_days:.2f},
    tidally_locked = {tidally_str},
    orbital_eccentricity = 0.05,
    
    -- Surface properties
    surface = {{
        composition = "{composition}",
        crater_count = {crater_count},
        albedo = 0.12,
        mean_temp_kelvin = 220,
    }},
    
    -- Formation
    formed_at_commit = {formed_at_commit},
    formed_by = "{formed_by}",   -- accretion, capture, impact
    
    -- State
    explored = false,
    colonies = 0,
}}

-- Helper functions
function Moon:get_display_name()
    return self.name or self.id
end

function Moon:get_surface_gravity()
    -- Returns gravity relative to Luna
    return self.mass_luna / ((self.radius_km / 1737) ^ 2)
end

function Moon:is_habitable()
    return self.surface.mean_temp_kelvin > 150 and 
           self.surface.mean_temp_kelvin < 400 and
           self.mass_luna > 0.01
end

function Moon:summary()
    local name = self:get_display_name()
    local gravity = self:get_surface_gravity()
    return string.format(
        "%s - %.0f km radius, %.2f Luna gravity, orbits %s",
        name, self.radius_km, gravity, self.parent_planet
    )
end

return Moon
'''
