"""
Python generator - Planets
"""

from typing import Optional


def generate_planet_py(
    planet_id: str,
    name: Optional[str] = None,
    planet_type: str = "terrestrial",
    mass_earth: float = 1.0,
    radius_earth: float = 1.0,
    orbit_au: float = 1.0,
    orbit_days: float = 365,
    moon_count: int = 0,
    has_atmosphere: bool = False,
    has_water: bool = False,
    has_life: bool = False,
    has_intelligent_life: bool = False,
    formed_at_commit: int = 0,
    axial_tilt: float = 23.4,
    day_length_hours: float = 24.0,
    surface_temp_kelvin: int = 288
) -> str:
    """Generate a planet.py file"""
    
    name_value = f'"{name}"' if name else "None"
    type_enum = planet_type.upper()
    
    return f'''"""
Planet Definition
Generated by Commit Universe Engine

{planet_id}
"""

from dataclasses import dataclass
from typing import Optional
from enum import Enum


class PlanetType(Enum):
    TERRESTRIAL = "terrestrial"
    GAS_GIANT = "gas_giant"
    ICE_GIANT = "ice_giant"
    DWARF = "dwarf"
    
    def is_rocky(self) -> bool:
        return self in (PlanetType.TERRESTRIAL, PlanetType.DWARF)
    
    def can_have_surface_life(self) -> bool:
        return self == PlanetType.TERRESTRIAL


@dataclass
class Planet:
    """Represents a planetary body"""
    id: str
    name: Optional[str]
    planet_type: PlanetType
    mass_earth: float
    radius_earth: float
    orbit_au: float
    orbit_days: float
    moon_count: int
    has_atmosphere: bool
    has_water: bool
    has_life: bool
    has_intelligent_life: bool
    formed_at_commit: int
    axial_tilt: float
    day_length_hours: float
    surface_temp_kelvin: int
    
    @property
    def gravity_earth(self) -> float:
        """Surface gravity relative to Earth"""
        return self.mass_earth / (self.radius_earth ** 2)
    
    @property
    def escape_velocity_km_s(self) -> float:
        """Escape velocity in km/s"""
        return 11.2 * (self.mass_earth / self.radius_earth) ** 0.5
    
    @property
    def is_habitable(self) -> bool:
        """Basic habitability check"""
        return (
            self.planet_type == PlanetType.TERRESTRIAL and
            self.has_atmosphere and
            self.has_water and
            200 < self.surface_temp_kelvin < 350
        )
    
    @property
    def display_name(self) -> str:
        return self.name or self.id


# Planet instance
PLANET_DATA = Planet(
    id="{planet_id}",
    name={name_value},
    planet_type=PlanetType.{type_enum},
    mass_earth={mass_earth:.4f},
    radius_earth={radius_earth:.4f},
    orbit_au={orbit_au:.4f},
    orbit_days={orbit_days:.2f},
    moon_count={moon_count},
    has_atmosphere={has_atmosphere},
    has_water={has_water},
    has_life={has_life},
    has_intelligent_life={has_intelligent_life},
    formed_at_commit={formed_at_commit},
    axial_tilt={axial_tilt:.1f},
    day_length_hours={day_length_hours:.2f},
    surface_temp_kelvin={surface_temp_kelvin}
)


if __name__ == "__main__":
    p = PLANET_DATA
    print(f"Planet: {{p.display_name}}")
    print(f"Type: {{p.planet_type.value}}")
    print(f"Habitable: {{p.is_habitable}}")
    print(f"Surface gravity: {{p.gravity_earth:.2f}}g")
'''
