"""
Rust generator - Galaxies
"""

from typing import Optional


def generate_galaxy_rs(
    galaxy_id: str,
    name: Optional[str] = None,
    galaxy_type: str = "Spiral",
    age_billion_years: float = 0,
    diameter_light_years: int = 50000,
    star_count: int = 0,
    formed_at_commit: int = 0,
    discovered_by: Optional[str] = None
) -> str:
    """Generate a galaxy.rs file"""
    
    name_value = f'Some("{name}".to_string())' if name else "None"
    discovered_value = f'Some("{discovered_by}".to_string())' if discovered_by else "None"
    galaxy_type_enum = galaxy_type.capitalize()
    
    return f'''//! Galaxy Definition
//! Generated by Commit Universe Engine

use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GalaxyType {{
    Spiral,
    Elliptical,
    Irregular,
    Lenticular,
}}

impl fmt::Display for GalaxyType {{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{
        match self {{
            GalaxyType::Spiral => write!(f, "Spiral"),
            GalaxyType::Elliptical => write!(f, "Elliptical"),
            GalaxyType::Irregular => write!(f, "Irregular"),
            GalaxyType::Lenticular => write!(f, "Lenticular"),
        }}
    }}
}}

#[derive(Debug, Clone)]
pub struct Galaxy {{
    pub id: String,
    pub name: Option<String>,
    pub classification: GalaxyType,
    pub age_billion_years: f64,
    pub diameter_light_years: u64,
    pub star_count: u64,
    pub formed_at_commit: u64,
    pub discovered_by: Option<String>,
}}

impl Galaxy {{
    pub fn is_named(&self) -> bool {{
        self.name.is_some()
    }}
    
    pub fn display_name(&self) -> String {{
        self.name.clone().unwrap_or_else(|| self.id.clone())
    }}
}}

// Galaxy instance
pub const GALAXY_DATA: Galaxy = Galaxy {{
    id: "{galaxy_id}",
    name: {name_value},
    classification: GalaxyType::{galaxy_type_enum},
    age_billion_years: {age_billion_years:.2f},
    diameter_light_years: {diameter_light_years},
    star_count: {star_count},
    formed_at_commit: {formed_at_commit},
    discovered_by: {discovered_value},
}};
'''
