"""
SQL generator - Universal registries and catalogs
"""

from typing import List, Dict, Optional


def generate_registry_sql(
    registry_type: str = "stars",
    created_at_commit: int = 0
) -> str:
    """Generate a new registry SQL file"""
    
    if registry_type == "stars":
        return _generate_star_registry(created_at_commit)
    elif registry_type == "planets":
        return _generate_planet_registry(created_at_commit)
    elif registry_type == "civilizations":
        return _generate_civilization_registry(created_at_commit)
    elif registry_type == "events":
        return _generate_events_registry(created_at_commit)
    else:
        return _generate_generic_registry(registry_type, created_at_commit)


def _generate_star_registry(created_at_commit: int) -> str:
    return f'''-- Universal Star Registry
-- Generated by Commit Universe Engine
-- Created at commit: {created_at_commit}

-- Schema version
CREATE TABLE IF NOT EXISTS schema_info (
    version INT PRIMARY KEY,
    created_at_commit BIGINT,
    description TEXT
);
INSERT INTO schema_info VALUES (1, {created_at_commit}, 'Initial star registry schema');

-- Main star catalog
CREATE TABLE IF NOT EXISTS stars (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128),
    galaxy_id VARCHAR(64) NOT NULL,
    sector_id VARCHAR(64) NOT NULL,
    system_path TEXT NOT NULL,
    
    -- Classification
    spectral_class CHAR(1) CHECK (spectral_class IN ('O','B','A','F','G','K','M')),
    luminosity_class VARCHAR(8),
    
    -- Physical properties
    mass_solar DECIMAL(12,6),
    radius_solar DECIMAL(12,6),
    luminosity_solar DECIMAL(16,6),
    temperature_kelvin INT,
    age_billion_years DECIMAL(8,4),
    
    -- State
    life_stage VARCHAR(32),
    planet_count INT DEFAULT 0,
    has_habitable_zone BOOLEAN DEFAULT FALSE,
    has_life BOOLEAN DEFAULT FALSE,
    has_civilization BOOLEAN DEFAULT FALSE,
    
    -- Metadata
    formed_at_commit BIGINT NOT NULL,
    last_updated_commit BIGINT,
    discovered_by VARCHAR(128),
    notes TEXT
);

-- Indexes for efficient queries
CREATE INDEX idx_stars_galaxy ON stars(galaxy_id);
CREATE INDEX idx_stars_spectral ON stars(spectral_class);
CREATE INDEX idx_stars_habitable ON stars(has_habitable_zone);
CREATE INDEX idx_stars_life ON stars(has_life);
CREATE INDEX idx_stars_civilization ON stars(has_civilization);

-- Useful views
CREATE VIEW habitable_stars AS
SELECT * FROM stars 
WHERE has_habitable_zone = TRUE 
AND life_stage = 'main_sequence'
AND spectral_class IN ('F', 'G', 'K');

CREATE VIEW civilized_systems AS
SELECT * FROM stars WHERE has_civilization = TRUE;

-- Sample data placeholder
-- INSERT statements will be appended by the engine
'''


def _generate_planet_registry(created_at_commit: int) -> str:
    return f'''-- Universal Planet Registry
-- Generated by Commit Universe Engine
-- Created at commit: {created_at_commit}

CREATE TABLE IF NOT EXISTS planets (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128),
    star_id VARCHAR(64) NOT NULL,
    planet_path TEXT NOT NULL,
    
    -- Classification
    planet_type VARCHAR(32),
    
    -- Physical properties
    mass_earth DECIMAL(12,6),
    radius_earth DECIMAL(12,6),
    density_g_cm3 DECIMAL(8,4),
    surface_gravity_g DECIMAL(8,4),
    
    -- Orbital properties
    orbit_au DECIMAL(12,6),
    orbit_days DECIMAL(12,2),
    eccentricity DECIMAL(8,6),
    
    -- Characteristics
    moon_count INT DEFAULT 0,
    ring_system BOOLEAN DEFAULT FALSE,
    has_atmosphere BOOLEAN DEFAULT FALSE,
    has_water BOOLEAN DEFAULT FALSE,
    has_life BOOLEAN DEFAULT FALSE,
    has_civilization BOOLEAN DEFAULT FALSE,
    
    -- Metadata
    formed_at_commit BIGINT NOT NULL,
    last_updated_commit BIGINT,
    
    FOREIGN KEY (star_id) REFERENCES stars(id)
);

CREATE INDEX idx_planets_star ON planets(star_id);
CREATE INDEX idx_planets_type ON planets(planet_type);
CREATE INDEX idx_planets_life ON planets(has_life);

CREATE VIEW habitable_planets AS
SELECT * FROM planets
WHERE planet_type = 'terrestrial'
AND has_atmosphere = TRUE
AND has_water = TRUE;
'''


def _generate_civilization_registry(created_at_commit: int) -> str:
    return f'''-- Universal Civilization Registry
-- Generated by Commit Universe Engine
-- Created at commit: {created_at_commit}

CREATE TABLE IF NOT EXISTS civilizations (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    species VARCHAR(128),
    homeworld_path TEXT NOT NULL,
    
    -- Status
    status VARCHAR(32) DEFAULT 'emerging',
    tech_level INT DEFAULT 0,
    government VARCHAR(64),
    
    -- Demographics
    population BIGINT DEFAULT 0,
    colony_count INT DEFAULT 0,
    
    -- History
    emerged_at_commit BIGINT NOT NULL,
    spaceflight_commit BIGINT,
    interstellar_commit BIGINT,
    extinct_at_commit BIGINT,
    
    -- Relations
    alliance_id VARCHAR(64),
    
    -- Metadata
    last_updated_commit BIGINT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS first_contacts (
    id SERIAL PRIMARY KEY,
    civ_a VARCHAR(64) NOT NULL,
    civ_b VARCHAR(64) NOT NULL,
    contact_commit BIGINT NOT NULL,
    outcome VARCHAR(32),  -- peaceful, hostile, neutral, trade
    notes TEXT,
    
    FOREIGN KEY (civ_a) REFERENCES civilizations(id),
    FOREIGN KEY (civ_b) REFERENCES civilizations(id)
);

CREATE INDEX idx_civs_status ON civilizations(status);
CREATE INDEX idx_civs_tech ON civilizations(tech_level);

CREATE VIEW active_civilizations AS
SELECT * FROM civilizations WHERE status NOT IN ('extinct', 'transcended');

CREATE VIEW spacefaring_civilizations AS
SELECT * FROM civilizations WHERE tech_level >= 4 AND status = 'active';
'''


def _generate_events_registry(created_at_commit: int) -> str:
    return f'''-- Universal Events Log
-- Generated by Commit Universe Engine
-- Created at commit: {created_at_commit}

CREATE TABLE IF NOT EXISTS cosmic_events (
    id SERIAL PRIMARY KEY,
    commit_number BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    scope VARCHAR(32),  -- universe, cluster, galaxy, system, planet, civilization
    location_path TEXT,
    
    -- Event details
    description TEXT NOT NULL,
    magnitude DECIMAL(8,2),  -- significance score
    
    -- Affected entities
    affected_stars TEXT[],
    affected_planets TEXT[],
    affected_civilizations TEXT[],
    
    -- Timestamps
    cosmic_age_myr DECIMAL(16,2),
    
    UNIQUE(commit_number, event_type, location_path)
);

CREATE INDEX idx_events_commit ON cosmic_events(commit_number);
CREATE INDEX idx_events_type ON cosmic_events(event_type);
CREATE INDEX idx_events_scope ON cosmic_events(scope);

-- Sample event types: 
-- supernova, nova, star_birth, planet_formation, abiogenesis,
-- evolution, extinction, civilization_emergence, first_contact,
-- war, peace, colony, transcendence
'''


def _generate_generic_registry(registry_type: str, created_at_commit: int) -> str:
    return f'''-- {registry_type.title()} Registry
-- Generated by Commit Universe Engine
-- Created at commit: {created_at_commit}

CREATE TABLE IF NOT EXISTS {registry_type} (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128),
    location_path TEXT,
    created_at_commit BIGINT NOT NULL,
    last_updated_commit BIGINT,
    data JSONB
);

CREATE INDEX idx_{registry_type}_created ON {registry_type}(created_at_commit);
'''


def append_registry_sql(
    registry_type: str,
    data: Dict,
    commit_number: int
) -> str:
    """Generate an INSERT statement to append to a registry"""
    
    if registry_type == "stars":
        return f'''
INSERT INTO stars (id, name, galaxy_id, sector_id, system_path, spectral_class, 
    mass_solar, life_stage, planet_count, has_life, has_civilization, formed_at_commit)
VALUES (
    '{data.get("id")}',
    {_sql_str(data.get("name"))},
    '{data.get("galaxy_id")}',
    '{data.get("sector_id")}',
    '{data.get("system_path")}',
    '{data.get("spectral_class", "G")}',
    {data.get("mass_solar", 1.0)},
    '{data.get("life_stage", "main_sequence")}',
    {data.get("planet_count", 0)},
    {_sql_bool(data.get("has_life", False))},
    {_sql_bool(data.get("has_civilization", False))},
    {commit_number}
) ON CONFLICT (id) DO UPDATE SET
    last_updated_commit = {commit_number},
    planet_count = EXCLUDED.planet_count,
    has_life = EXCLUDED.has_life,
    has_civilization = EXCLUDED.has_civilization;
'''
    
    # Generic fallback
    return f"-- TODO: Generate {registry_type} insert for {data.get('id')}"


def _sql_str(value: Optional[str]) -> str:
    """Convert Python string to SQL string or NULL"""
    return f"'{value}'" if value else "NULL"


def _sql_bool(value: bool) -> str:
    """Convert Python bool to SQL bool"""
    return "TRUE" if value else "FALSE"
