"""
TOML generator - Galaxy clusters
"""

from typing import Optional


def generate_cluster_toml(
    cluster_id: str,
    name: Optional[str] = None,
    formed_at_commit: int = 0,
    age_billion_years: float = 0,
    position: tuple = (0.0, 0.0, 0.0),
    galaxy_count: int = 0,
    total_mass_solar: float = 0,
    diameter_mly: float = 0
) -> str:
    """Generate a cluster.toml file"""
    
    name_line = f'name = "{name}"' if name else "# name = unnamed"
    
    return f'''# Galaxy Cluster Definition
# Generated by Commit Universe Engine

[cluster]
id = "{cluster_id}"
{name_line}
formed_at_commit = {formed_at_commit}
age_billion_years = {age_billion_years:.2f}

[cluster.position]
x = {position[0]:.6f}
y = {position[1]:.6f}
z = {position[2]:.6f}

[cluster.stats]
galaxy_count = {galaxy_count}
total_mass_solar = {total_mass_solar:.2e}
diameter_mly = {diameter_mly:.2f}

[cluster.metadata]
last_updated_commit = {formed_at_commit}
notable_features = []
'''
