"""
TOML generator - Galaxy clusters
"""

import re
from pathlib import Path
from typing import Optional


def update_cluster_stats(cluster_path: Path, galaxy_count: int = None,
                         total_mass_solar: float = None, diameter_mly: float = None,
                         last_updated_commit: int = None) -> str:
    """Read and update cluster.toml stats, return new content"""
    content = cluster_path.read_text()

    if galaxy_count is not None:
        content = re.sub(
            r'galaxy_count = \d+',
            f'galaxy_count = {galaxy_count}',
            content
        )

    if total_mass_solar is not None:
        content = re.sub(
            r'total_mass_solar = [\d.e+-]+',
            f'total_mass_solar = {total_mass_solar:.2e}',
            content
        )

    if diameter_mly is not None:
        content = re.sub(
            r'diameter_mly = [\d.]+',
            f'diameter_mly = {diameter_mly:.2f}',
            content
        )

    if last_updated_commit is not None:
        content = re.sub(
            r'last_updated_commit = \d+',
            f'last_updated_commit = {last_updated_commit}',
            content
        )

    return content


def get_cluster_galaxy_count(cluster_path: Path) -> int:
    """Read current galaxy count from cluster.toml"""
    content = cluster_path.read_text()
    match = re.search(r'galaxy_count = (\d+)', content)
    return int(match.group(1)) if match else 0


def generate_cluster_toml(
    cluster_id: str,
    name: Optional[str] = None,
    formed_at_commit: int = 0,
    last_updated_commit: int = None,
    age_billion_years: float = 0,
    position: tuple = (0.0, 0.0, 0.0),
    galaxy_count: int = 0,
    total_mass_solar: float = 0,
    diameter_mly: float = 0
) -> str:
    """Generate a cluster.toml file"""

    name_line = f'name = "{name}"' if name else "# name = unnamed"
    if last_updated_commit is None:
        last_updated_commit = formed_at_commit

    return f'''# Galaxy Cluster Definition
# Generated by Commit Universe Engine

[cluster]
id = "{cluster_id}"
{name_line}
formed_at_commit = {formed_at_commit}
age_billion_years = {age_billion_years:.2f}

[cluster.position]
x = {position[0]:.6f}
y = {position[1]:.6f}
z = {position[2]:.6f}

[cluster.stats]
galaxy_count = {galaxy_count}
total_mass_solar = {total_mass_solar:.2e}
diameter_mly = {diameter_mly:.2f}

[cluster.metadata]
last_updated_commit = {last_updated_commit}
notable_features = []
'''
