"""
TypeScript generator - Civilizations

Generates comprehensive civilization files with:
- 16-age progression system
- Religions and belief systems
- Cultures and traditions
- Governments and politics
- Technology discoveries
- Relations with other civs
"""

from typing import List, Optional, Dict, Any
import json


def generate_civilization_ts(
    # Identity
    civ_id: str,
    name: str,
    species_name: str,
    language_family: str = "melodic",

    # Location
    homeworld: str = "",
    home_star: str = "",
    home_galaxy: str = "",
    controlled_systems: Optional[List[str]] = None,
    colonies: Optional[List[Dict]] = None,

    # Timeline
    emerged_at_commit: int = 0,
    current_age: str = "prehistoric",
    age_history: Optional[List[Dict]] = None,

    # Demographics
    population: int = 10000,
    population_growth_rate: float = 0.01,

    # Society
    government: str = "tribe",
    government_history: Optional[List[Dict]] = None,
    religions: Optional[List[Dict]] = None,
    cultures: Optional[List[Dict]] = None,
    factions: Optional[List[Dict]] = None,

    # Technology
    tech_discoveries: Optional[List[Dict]] = None,
    current_tech_focus: str = "survival",

    # External
    known_civs: Optional[List[Dict]] = None,
    active_wars: Optional[List[Dict]] = None,
    active_treaties: Optional[List[Dict]] = None,

    # Status
    status: str = "emerging",
    golden_ages: int = 0,
    dark_ages: int = 0,

    # Traits
    traits: Optional[List[str]] = None,

    # Discovered by (if contacted)
    discovered_by: Optional[str] = None,
) -> str:
    """Generate a comprehensive civilization.ts file"""

    # Defaults
    if controlled_systems is None:
        controlled_systems = []
    if colonies is None:
        colonies = []
    if age_history is None:
        age_history = [{"age": "prehistoric", "started_at_commit": emerged_at_commit}]
    if government_history is None:
        government_history = [{"type": government, "started_at_commit": emerged_at_commit}]
    if religions is None:
        religions = []
    if cultures is None:
        cultures = []
    if factions is None:
        factions = []
    if tech_discoveries is None:
        tech_discoveries = []
    if known_civs is None:
        known_civs = []
    if active_wars is None:
        active_wars = []
    if active_treaties is None:
        active_treaties = []
    if traits is None:
        traits = ["adaptive"]

    # Format arrays
    controlled_str = json.dumps(controlled_systems)
    colonies_str = _format_colonies(colonies)
    age_history_str = _format_age_history(age_history)
    gov_history_str = _format_gov_history(government_history)
    religions_str = _format_religions(religions)
    cultures_str = _format_cultures(cultures)
    factions_str = _format_factions(factions)
    tech_str = _format_tech(tech_discoveries)
    known_civs_str = _format_known_civs(known_civs)
    wars_str = _format_wars(active_wars)
    treaties_str = _format_treaties(active_treaties)
    traits_str = json.dumps(traits)
    discovered_str = f'"{discovered_by}"' if discovered_by else "null"

    return f'''/**
 * Civilization Definition: {name}
 * Generated by Commit Universe Engine
 *
 * Species: {species_name}
 * Current Age: {current_age.replace("_", " ").title()}
 * Status: {status.title()}
 */

// ============ TYPE DEFINITIONS ============

interface Civilization {{
    // Identity
    id: string;
    name: string;
    species_name: string;
    language_family: string;

    // Location
    homeworld: string;
    home_star: string;
    home_galaxy: string;
    controlled_systems: string[];
    colonies: Colony[];

    // Timeline
    emerged_at_commit: number;
    current_age: Age;
    age_history: AgeTransition[];

    // Demographics
    population: number;
    population_growth_rate: number;

    // Society
    government: Government;
    government_history: GovernmentChange[];
    religions: Religion[];
    cultures: Culture[];
    factions: Faction[];

    // Technology
    tech_discoveries: Discovery[];
    current_tech_focus: string;

    // External Relations
    known_civs: CivRelation[];
    active_wars: War[];
    active_treaties: Treaty[];

    // Status
    status: CivStatus;
    golden_ages: number;
    dark_ages: number;
    traits: string[];
    discovered_by: string | null;
}}

// Age system - 16 stages from prehistoric to transcendent
type Age =
    | "prehistoric"     // Hunter-gatherers, fire, basic tools
    | "tribal"          // Organized tribes, shamanism, oral tradition
    | "bronze"          // Early metallurgy, first cities, writing
    | "iron"            // Advanced metallurgy, empires, philosophy
    | "classical"       // Golden age of culture, mathematics
    | "medieval"        // Feudalism, organized religion dominates
    | "renaissance"     // Scientific revolution, exploration
    | "industrial"      // Machines, urbanization, nation-states
    | "modern"          // Electricity, global communication
    | "atomic"          // Nuclear power, computing, cold wars
    | "information"     // Digital revolution, global networks
    | "space"           // First spaceflight, orbital presence
    | "interplanetary"  // Colony ships, solar system colonization
    | "interstellar"    // FTL or generation ships, nearby stars
    | "galactic"        // Galaxy-spanning presence
    | "transcendent";   // Post-physical, ascended

interface AgeTransition {{
    age: Age;
    started_at_commit: number;
    catalyst?: string;  // What caused the transition
}}

type CivStatus =
    | "emerging"        // Just achieved sapience
    | "developing"      // Building civilization
    | "active"          // Thriving
    | "golden_age"      // Peak prosperity
    | "stagnant"        // Not advancing
    | "declining"       // Losing ground
    | "civil_war"       // Internal conflict
    | "dormant"         // Hibernating/hiding
    | "subjugated"      // Conquered by another
    | "extinct"         // Gone
    | "transcended";    // Evolved beyond physical form

// Government types available at different ages
type Government =
    // Early
    | "band" | "tribe" | "chiefdom" | "tribal_council" | "elder_rule"
    // Ancient
    | "city_state" | "early_kingdom" | "theocracy" | "pharaonic"
    | "empire" | "republic" | "oligarchy" | "military_state"
    | "democracy" | "bureaucratic_empire" | "senatorial_republic"
    // Medieval/Renaissance
    | "feudalism" | "absolute_monarchy" | "religious_state" | "khanate"
    | "constitutional_monarchy" | "merchant_republic" | "colonial_empire"
    // Industrial/Modern
    | "nation_state" | "constitutional_democracy" | "communist_state" | "fascist_state"
    | "liberal_democracy" | "authoritarian" | "one_party_state" | "federal_republic"
    // Space Age+
    | "superpower_bloc" | "military_junta" | "technocracy"
    | "corporate_state" | "direct_democracy" | "surveillance_state" | "cyber_democracy"
    | "planetary_government" | "orbital_corporate" | "space_federation"
    | "system_federation" | "colonial_administration" | "corporate_hegemony"
    | "stellar_empire" | "confederation" | "trade_league" | "hive_consensus"
    | "galactic_council" | "galactic_empire" | "transcendent_collective"
    | "post_physical" | "unity_consciousness";

interface GovernmentChange {{
    type: Government;
    started_at_commit: number;
    ended_at_commit?: number;
    cause?: string;  // revolution, reform, conquest, etc.
}}

// Religion system
type ReligionType =
    | "animistic"        // Nature spirits
    | "ancestor_worship" // Veneration of ancestors
    | "polytheistic"     // Many gods
    | "monotheistic"     // One god
    | "dualistic"        // Two opposing forces
    | "philosophical"    // Ethics-based, non-theistic
    | "cosmic"           // Worship of cosmic forces
    | "machine_cult"     // Technology worship
    | "transcendent";    // Post-physical spirituality

interface Religion {{
    id: string;
    name: string;
    type: ReligionType;
    founder: string | null;
    founded_at_commit: number;
    adherent_percentage: number;
    core_beliefs: string[];
    holy_sites: string[];
    status: "emerging" | "growing" | "dominant" | "declining" | "underground" | "extinct";
}}

// Culture system
interface Culture {{
    id: string;
    name: string;
    parent_culture: string | null;
    emerged_at_commit: number;
    values: string[];
    art_forms: string[];
    taboos: string[];
    population_percentage: number;
}}

// Faction system
interface Faction {{
    id: string;
    name: string;
    ideology: string;
    power_level: number;  // 0-100
    leader: string | null;
    goals: string[];
    founded_at_commit: number;
}}

// Technology
interface Discovery {{
    id: string;
    name: string;
    category: string;
    discovered_at_commit: number;
    discoverer?: string;
    impact: string;
}}

// Colony
interface Colony {{
    location: string;
    name: string;
    founded_at_commit: number;
    population: number;
    status: "founding" | "growing" | "established" | "thriving" | "declining" | "abandoned";
}}

// External relations
interface CivRelation {{
    civ_id: string;
    civ_name: string;
    first_contact_commit: number;
    status: "unknown" | "hostile" | "cold" | "neutral" | "warm" | "friendly" | "allied";
    trade_active: boolean;
}}

interface War {{
    id: string;
    name: string;
    opponent_id: string;
    opponent_name: string;
    started_at_commit: number;
    cause: string;
    battles: number;
    our_casualties: number;
    their_casualties: number;
}}

interface Treaty {{
    id: string;
    name: string;
    partner_id: string;
    partner_name: string;
    signed_at_commit: number;
    type: "peace" | "trade" | "alliance" | "non_aggression" | "mutual_defense";
    terms: string[];
}}

// ============ CIVILIZATION DATA ============

const civilization: Civilization = {{
    // Identity
    id: "{civ_id}",
    name: "{name}",
    species_name: "{species_name}",
    language_family: "{language_family}",

    // Location
    homeworld: "{homeworld}",
    home_star: "{home_star}",
    home_galaxy: "{home_galaxy}",
    controlled_systems: {controlled_str},
    colonies: {colonies_str},

    // Timeline
    emerged_at_commit: {emerged_at_commit},
    current_age: "{current_age}",
    age_history: {age_history_str},

    // Demographics
    population: {population:_},
    population_growth_rate: {population_growth_rate},

    // Society
    government: "{government}",
    government_history: {gov_history_str},
    religions: {religions_str},
    cultures: {cultures_str},
    factions: {factions_str},

    // Technology
    tech_discoveries: {tech_str},
    current_tech_focus: "{current_tech_focus}",

    // External Relations
    known_civs: {known_civs_str},
    active_wars: {wars_str},
    active_treaties: {treaties_str},

    // Status
    status: "{status}",
    golden_ages: {golden_ages},
    dark_ages: {dark_ages},
    traits: {traits_str},
    discovered_by: {discovered_str}
}};

// ============ HELPER FUNCTIONS ============

function getAgeIndex(age: Age): number {{
    const ages: Age[] = [
        "prehistoric", "tribal", "bronze", "iron", "classical",
        "medieval", "renaissance", "industrial", "modern", "atomic",
        "information", "space", "interplanetary", "interstellar",
        "galactic", "transcendent"
    ];
    return ages.indexOf(age);
}}

function canAchieveSpaceflight(civ: Civilization): boolean {{
    return getAgeIndex(civ.current_age) >= getAgeIndex("space") ||
           (getAgeIndex(civ.current_age) >= getAgeIndex("atomic") && civ.status !== "extinct");
}}

function canAchieveInterstellar(civ: Civilization): boolean {{
    return getAgeIndex(civ.current_age) >= getAgeIndex("interstellar");
}}

function getDominantReligion(civ: Civilization): Religion | null {{
    if (civ.religions.length === 0) return null;
    return civ.religions.reduce((a, b) =>
        a.adherent_percentage > b.adherent_percentage ? a : b
    );
}}

function getDominantCulture(civ: Civilization): Culture | null {{
    if (civ.cultures.length === 0) return null;
    return civ.cultures.reduce((a, b) =>
        a.population_percentage > b.population_percentage ? a : b
    );
}}

function getInfluence(civ: Civilization): number {{
    const ageBonus = getAgeIndex(civ.current_age) * 1000;
    const popBonus = Math.log10(civ.population + 1) * 100;
    const colonyBonus = civ.colonies.length * 500;
    const systemBonus = civ.controlled_systems.length * 200;
    return ageBonus + popBonus + colonyBonus + systemBonus;
}}

function isAtWar(civ: Civilization): boolean {{
    return civ.active_wars.length > 0;
}}

function getTotalColonyPopulation(civ: Civilization): number {{
    return civ.colonies.reduce((sum, c) => sum + c.population, 0);
}}

function getSummary(civ: Civilization): string {{
    return `${{civ.name}} (${{civ.species_name}}): ${{civ.current_age}} age, ` +
           `pop ${{civ.population.toLocaleString()}}, ${{civ.status}}`;
}}

// ============ EXPORTS ============

export {{
    civilization,
    Civilization,
    Age,
    CivStatus,
    Government,
    Religion,
    Culture,
    Faction,
    Discovery,
    Colony,
    CivRelation,
    War,
    Treaty,
    getAgeIndex,
    canAchieveSpaceflight,
    canAchieveInterstellar,
    getDominantReligion,
    getDominantCulture,
    getInfluence,
    isAtWar,
    getTotalColonyPopulation,
    getSummary
}};
'''


# Helper functions for formatting

def _format_colonies(colonies: List[Dict]) -> str:
    if not colonies:
        return "[]"
    items = []
    for c in colonies:
        items.append(f'''{{
            location: "{c.get('location', '')}",
            name: "{c.get('name', 'Unnamed')}",
            founded_at_commit: {c.get('founded_at_commit', 0)},
            population: {c.get('population', 0)},
            status: "{c.get('status', 'founding')}"
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_age_history(history: List[Dict]) -> str:
    if not history:
        return "[]"
    items = []
    for h in history:
        catalyst = f', catalyst: "{h["catalyst"]}"' if h.get("catalyst") else ""
        items.append(f'{{ age: "{h["age"]}", started_at_commit: {h["started_at_commit"]}{catalyst} }}')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_gov_history(history: List[Dict]) -> str:
    if not history:
        return "[]"
    items = []
    for h in history:
        ended = f', ended_at_commit: {h["ended_at_commit"]}' if h.get("ended_at_commit") else ""
        cause = f', cause: "{h["cause"]}"' if h.get("cause") else ""
        items.append(f'{{ type: "{h["type"]}", started_at_commit: {h["started_at_commit"]}{ended}{cause} }}')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_religions(religions: List[Dict]) -> str:
    if not religions:
        return "[]"
    items = []
    for r in religions:
        founder = f'"{r["founder"]}"' if r.get("founder") else "null"
        beliefs = json.dumps(r.get("core_beliefs", []))
        sites = json.dumps(r.get("holy_sites", []))
        items.append(f'''{{
            id: "{r.get('id', '')}",
            name: "{r.get('name', 'Unknown')}",
            type: "{r.get('type', 'animistic')}",
            founder: {founder},
            founded_at_commit: {r.get('founded_at_commit', 0)},
            adherent_percentage: {r.get('adherent_percentage', 0)},
            core_beliefs: {beliefs},
            holy_sites: {sites},
            status: "{r.get('status', 'emerging')}"
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_cultures(cultures: List[Dict]) -> str:
    if not cultures:
        return "[]"
    items = []
    for c in cultures:
        parent = f'"{c["parent_culture"]}"' if c.get("parent_culture") else "null"
        values = json.dumps(c.get("values", []))
        arts = json.dumps(c.get("art_forms", []))
        taboos = json.dumps(c.get("taboos", []))
        items.append(f'''{{
            id: "{c.get('id', '')}",
            name: "{c.get('name', 'Unknown')}",
            parent_culture: {parent},
            emerged_at_commit: {c.get('emerged_at_commit', 0)},
            values: {values},
            art_forms: {arts},
            taboos: {taboos},
            population_percentage: {c.get('population_percentage', 100)}
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_factions(factions: List[Dict]) -> str:
    if not factions:
        return "[]"
    items = []
    for f in factions:
        leader = f'"{f["leader"]}"' if f.get("leader") else "null"
        goals = json.dumps(f.get("goals", []))
        items.append(f'''{{
            id: "{f.get('id', '')}",
            name: "{f.get('name', 'Unknown')}",
            ideology: "{f.get('ideology', 'moderate')}",
            power_level: {f.get('power_level', 50)},
            leader: {leader},
            goals: {goals},
            founded_at_commit: {f.get('founded_at_commit', 0)}
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_tech(tech: List[Dict]) -> str:
    if not tech:
        return "[]"
    items = []
    for t in tech:
        discoverer = f', discoverer: "{t["discoverer"]}"' if t.get("discoverer") else ""
        items.append(f'''{{
            id: "{t.get('id', '')}",
            name: "{t.get('name', 'Unknown')}",
            category: "{t.get('category', 'survival')}",
            discovered_at_commit: {t.get('discovered_at_commit', 0)}{discoverer},
            impact: "{t.get('impact', 'minor')}"
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_known_civs(civs: List[Dict]) -> str:
    if not civs:
        return "[]"
    items = []
    for c in civs:
        items.append(f'''{{
            civ_id: "{c.get('civ_id', '')}",
            civ_name: "{c.get('civ_name', 'Unknown')}",
            first_contact_commit: {c.get('first_contact_commit', 0)},
            status: "{c.get('status', 'neutral')}",
            trade_active: {str(c.get('trade_active', False)).lower()}
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_wars(wars: List[Dict]) -> str:
    if not wars:
        return "[]"
    items = []
    for w in wars:
        items.append(f'''{{
            id: "{w.get('id', '')}",
            name: "{w.get('name', 'Unknown War')}",
            opponent_id: "{w.get('opponent_id', '')}",
            opponent_name: "{w.get('opponent_name', 'Unknown')}",
            started_at_commit: {w.get('started_at_commit', 0)},
            cause: "{w.get('cause', 'unknown')}",
            battles: {w.get('battles', 0)},
            our_casualties: {w.get('our_casualties', 0)},
            their_casualties: {w.get('their_casualties', 0)}
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


def _format_treaties(treaties: List[Dict]) -> str:
    if not treaties:
        return "[]"
    items = []
    for t in treaties:
        terms = json.dumps(t.get("terms", []))
        items.append(f'''{{
            id: "{t.get('id', '')}",
            name: "{t.get('name', 'Treaty')}",
            partner_id: "{t.get('partner_id', '')}",
            partner_name: "{t.get('partner_name', 'Unknown')}",
            signed_at_commit: {t.get('signed_at_commit', 0)},
            type: "{t.get('type', 'peace')}",
            terms: {terms}
        }}''')
    return "[\n        " + ",\n        ".join(items) + "\n    ]"


# Legacy compatibility
def _tech_level_name(level: int) -> str:
    """Convert old tech level int to age name"""
    ages = [
        "prehistoric", "tribal", "bronze", "iron", "classical",
        "medieval", "renaissance", "industrial", "modern", "atomic",
        "information", "space", "interplanetary", "interstellar",
        "galactic", "transcendent"
    ]
    return ages[min(level, len(ages) - 1)]
