"""
TypeScript generator - Civilizations
"""

from typing import List, Optional


def generate_civilization_ts(
    civ_id: str,
    name: str,
    species: str,
    homeworld: str,
    emerged_at_commit: int = 0,
    tech_level: int = 0,
    population: int = 0,
    colonies: Optional[List[str]] = None,
    traits: Optional[List[str]] = None,
    status: str = "emerging",
    government: str = "tribal",
    discovered_by: Optional[str] = None,
    allies: Optional[List[str]] = None,
    at_war_with: Optional[List[str]] = None
) -> str:
    """Generate a civilization.ts file"""
    
    if colonies is None:
        colonies = []
    if traits is None:
        traits = ["adaptive"]
    if allies is None:
        allies = []
    if at_war_with is None:
        at_war_with = []
    
    colonies_str = ", ".join([f'"{c}"' for c in colonies])
    traits_str = ", ".join([f'"{t}"' for t in traits])
    allies_str = ", ".join([f'"{a}"' for a in allies])
    enemies_str = ", ".join([f'"{e}"' for e in at_war_with])
    discovered_str = f'"{discovered_by}"' if discovered_by else "null"
    
    return f'''/**
 * Civilization Definition
 * Generated by Commit Universe Engine
 * 
 * {name}
 */

// Type definitions
interface Civilization {{
    id: string;
    name: string;
    species: string;
    homeworld: string;
    emerged_at_commit: number;
    tech_level: TechLevel;
    population: number;
    colonies: string[];
    traits: CivTrait[];
    status: CivStatus;
    government: GovernmentType;
    discovered_by: string | null;
    diplomacy: {{
        allies: string[];
        at_war_with: string[];
    }};
}}

enum TechLevel {{
    Stone = 0,
    Agricultural = 1,
    Industrial = 2,
    Atomic = 3,
    Spacefaring = 4,
    Interstellar = 5,
    Galactic = 6,
    Transcendent = 7
}}

type CivTrait = 
    | "curious" | "aggressive" | "peaceful" | "isolationist"
    | "expansionist" | "spiritual" | "logical" | "artistic"
    | "long-lived" | "short-lived" | "hive-mind" | "individualist"
    | "adaptive" | "stubborn" | "cooperative" | "competitive"
    | "telepathic" | "mechanized" | "aquatic" | "subterranean";

type CivStatus = 
    | "emerging"      // Just achieved sapience
    | "developing"    // Building civilization
    | "active"        // Thriving
    | "golden_age"    // Peak prosperity
    | "stagnant"      // Not advancing
    | "declining"     // Losing ground
    | "dormant"       // Hibernating/hiding
    | "extinct"       // Gone
    | "transcended";  // Evolved beyond physical form

type GovernmentType =
    | "tribal"
    | "monarchy"
    | "republic"
    | "democracy"
    | "oligarchy"
    | "theocracy"
    | "hive_mind"
    | "ai_governed"
    | "anarchist"
    | "corporate";

// Civilization instance
const civilization: Civilization = {{
    id: "{civ_id}",
    name: "{name}",
    species: "{species}",
    homeworld: "{homeworld}",
    emerged_at_commit: {emerged_at_commit},
    tech_level: TechLevel.{_tech_level_name(tech_level)},
    population: {population:_},
    colonies: [{colonies_str}],
    traits: [{traits_str}],
    status: "{status}",
    government: "{government}",
    discovered_by: {discovered_str},
    diplomacy: {{
        allies: [{allies_str}],
        at_war_with: [{enemies_str}]
    }}
}};

// Helper functions
function getTechLevelName(level: TechLevel): string {{
    return TechLevel[level];
}}

function canAchieveSpaceflight(civ: Civilization): boolean {{
    return civ.tech_level >= TechLevel.Atomic && civ.status !== "extinct";
}}

function canAchieveInterstellar(civ: Civilization): boolean {{
    return civ.tech_level >= TechLevel.Spacefaring && civ.colonies.length > 0;
}}

function getInfluence(civ: Civilization): number {{
    const techBonus = civ.tech_level * 1000;
    const popBonus = Math.log10(civ.population + 1) * 100;
    const colonyBonus = civ.colonies.length * 500;
    return techBonus + popBonus + colonyBonus;
}}

// Exports
export {{ 
    civilization,
    Civilization,
    TechLevel,
    CivTrait,
    CivStatus,
    GovernmentType,
    getTechLevelName,
    canAchieveSpaceflight,
    canAchieveInterstellar,
    getInfluence
}};
'''


def _tech_level_name(level: int) -> str:
    """Convert tech level int to enum name"""
    names = [
        "Stone", "Agricultural", "Industrial", "Atomic",
        "Spacefaring", "Interstellar", "Galactic", "Transcendent"
    ]
    return names[min(level, len(names) - 1)]
