//! Galaxy Definition
//! Generated by Commit Universe Engine

use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GalaxyType {
    Spiral,
    Elliptical,
    Irregular,
    Lenticular,
}

impl fmt::Display for GalaxyType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GalaxyType::Spiral => write!(f, "Spiral"),
            GalaxyType::Elliptical => write!(f, "Elliptical"),
            GalaxyType::Irregular => write!(f, "Irregular"),
            GalaxyType::Lenticular => write!(f, "Lenticular"),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Galaxy {
    pub id: String,
    pub name: Option<String>,
    pub classification: GalaxyType,
    pub age_billion_years: f64,
    pub diameter_light_years: u64,
    pub star_count: u64,
    pub formed_at_commit: u64,
    pub discovered_by: Option<String>,
}

impl Galaxy {
    pub fn is_named(&self) -> bool {
        self.name.is_some()
    }
    
    pub fn display_name(&self) -> String {
        self.name.clone().unwrap_or_else(|| self.id.clone())
    }
}

// Galaxy instance
pub const GALAXY_DATA: Galaxy = Galaxy {
    id: "galaxy-1177",
    name: Some("PGC 6606".to_string()),
    classification: GalaxyType::Spiral,
    age_billion_years: 0.00,
    diameter_light_years: 69929,
    star_count: 0,
    formed_at_commit: 545,
    discovered_by: None,
};
