/**
 * Star System Definition
 * Generated by Commit Universe Engine
 * 
 * system-5154
 */

#ifndef STAR_SYSTEM_5154_H
#define STAR_SYSTEM_5154_H

/* Spectral Classifications */
typedef enum {
    SPECTRAL_O,  /* Blue giants, >30,000K */
    SPECTRAL_B,  /* Blue-white, 10,000-30,000K */
    SPECTRAL_A,  /* White, 7,500-10,000K */
    SPECTRAL_F,  /* Yellow-white, 6,000-7,500K */
    SPECTRAL_G,  /* Yellow (Sun-like), 5,200-6,000K */
    SPECTRAL_K,  /* Orange, 3,700-5,200K */
    SPECTRAL_M   /* Red dwarfs, 2,400-3,700K */
} SpectralClass;

/* Stellar Evolution Stages */
typedef enum {
    STAGE_PROTOSTAR,
    STAGE_MAIN_SEQUENCE,
    STAGE_SUBGIANT,
    STAGE_RED_GIANT,
    STAGE_HORIZONTAL_BRANCH,
    STAGE_ASYMPTOTIC_GIANT,
    STAGE_PLANETARY_NEBULA,
    STAGE_WHITE_DWARF,
    STAGE_NEUTRON_STAR,
    STAGE_BLACK_HOLE
} LifeStage;

/* Star Data Structure */
struct Star {
    char            id[32];
    char            name[64];
    SpectralClass   spectral_class;
    double          mass_solar;
    double          age_billion_years;
    LifeStage       life_stage;
    int             planet_count;
    double          habitable_zone_inner_au;
    double          habitable_zone_outer_au;
    double          luminosity_solar;
    int             temperature_kelvin;
    unsigned long   formed_at_commit;
};

/* Star Instance */
static const struct Star STAR_DATA = {
    .id                     = "system-5154",
    .name                   = "TYC 627524 Ab",
    .spectral_class         = SPECTRAL_M,
    .mass_solar             = 0.3205,
    .age_billion_years      = 0.00,
    .life_stage             = STAGE_MAIN_SEQUENCE,
    .planet_count           = 0,
    .habitable_zone_inner_au = 0.90,
    .habitable_zone_outer_au = 1.40,
    .luminosity_solar       = 1.0000,
    .temperature_kelvin     = 5778,
    .formed_at_commit       = 545
};

/* Helper Functions */
static inline int star_has_name(const struct Star* s) {
    return s->name[0] != '\0';
}

static inline int star_is_habitable(const struct Star* s) {
    return s->life_stage == STAGE_MAIN_SEQUENCE && 
           s->spectral_class >= SPECTRAL_F && 
           s->spectral_class <= SPECTRAL_K;
}

#endif /* STAR_SYSTEM_5154_H */
